import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem-vindo ao <a href="https://www.instagram.com/desesperodacomputacao/">Desespero da Computação!</a>
        </h1>

        <p className={styles.description}>
          Veja alguns links que eu separei para você:{' '}
        </p>

        <div className={styles.grid}>
          <a href="https://www.youtube.com/channel/UCWS2lchXFtLEudFMjAyiUtw" className={styles.card}>
            <h2>YouTube &rarr;</h2>
            <p>Acompanhe nossos vídeos através do YouTube.</p>
          </a>

          <a href="https://forms.gle/tAkn2oKsSNuufmFv5" className={styles.card}>
            <h2>Curso de Python&rarr;</h2>
            <p>Se inscreva na lista de espera para no nosso curso de Python.</p>
          </a>

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
